
%% Optimization Settings
% Set nondefault solver options
options = optimoptions("ga","PopulationSize",250, ...
                            "MaxGenerations",100,...
                            "MaxStallGenerations",20,... 
                            "UseParallel",true, ...
                            "ConstraintTolerance",0.1, ...
                            "Display","iter", ...
                            "PlotFcn",["gaplotdistance","gaplotselection","gaplotscorediversity",...
    "gaplotscores","gaplotstopping","gaplotbestf","gaplotbestindiv",...
    "gaplotexpectation","gaplotrange"]);

%% RUN Genetic Algorithm
% Solve
[solution,objectiveValue] = ga(@optimization_cost_with_penalty,...
    number_of_inputs,[],[],[],[],lower_bounds,upper_bounds,[],IntCon,...
    options);

% Clear variables
clearvars options